export const getUserByIdMockData = {
	"login": "alexcoroza",
	"id": 16507120,
	"node_id": "MDQ6VXNlcjE2NTA3MTIw",
	"avatar_url": "https://avatars2.githubusercontent.com/u/16507120?v=4",
	"gravatar_id": "",
	"url": "https://api.github.com/users/alexcoroza",
	"html_url": "https://github.com/alexcoroza",
	"followers_url": "https://api.github.com/users/alexcoroza/followers",
	"following_url": "https://api.github.com/users/alexcoroza/following{/other_user}",
	"gists_url": "https://api.github.com/users/alexcoroza/gists{/gist_id}",
	"starred_url": "https://api.github.com/users/alexcoroza/starred{/owner}{/repo}",
	"subscriptions_url": "https://api.github.com/users/alexcoroza/subscriptions",
	"organizations_url": "https://api.github.com/users/alexcoroza/orgs",
	"repos_url": "https://api.github.com/users/alexcoroza/repos",
	"events_url": "https://api.github.com/users/alexcoroza/events{/privacy}",
	"received_events_url": "https://api.github.com/users/alexcoroza/received_events",
	"type": "User",
	"site_admin": false,
	"name": "Alex Coroza",
	"company": "Cambridge Assessment",
	"blog": "",
	"location": null,
	"email": null,
	"hireable": null,
	"bio": "Web Developer",
	"public_repos": 2,
	"public_gists": 0,
	"followers": 0,
	"following": 0,
	"created_at": "2016-01-01T07:15:36Z",
	"updated_at": "2019-12-10T06:24:34Z"
}